-- ============================================================
--  NEXO-UD  |  V6__add_more_study_plans.sql
--  Insert or update 66 study plans
-- ============================================================

INSERT INTO study_plans (codigo_plan, nombre, facultad) VALUES
('005', 'Ingeniería Electrónica', 'Facultad de Ingeniería'),
('007', 'Ingeniería Eléctrica', 'Facultad de Ingeniería'),
('015', 'Ingeniería Industrial', 'Facultad de Ingeniería'),
('020', 'Ingeniería de Sistemas', 'Facultad de Ingeniería'),
('025', 'Ingeniería Catastral y Geodesia', 'Facultad de Ingeniería'),
('372', 'INGENIERIA ELECTRICA (CICLOS PROPEDEUTICOS)', 'Facultad Tecnológica'),
('373', 'INGENIERIA EN TELECOMUNICACIONES (CICLOS PROPEDEUTICOS)', 'Facultad Tecnológica'),
('375', 'INGENIERIA MECANICA (CICLOS PROPEDEUTICOS)', 'Facultad Tecnológica'),
('377', 'INGENIERIA DE PRODUCCION (CICLOS PROPEDEUTICOS)', 'Facultad Tecnológica'),
('379', 'Tecnología en Construcciones Civiles', 'Facultad Tecnológica'),
('572', 'Tecnología en Electricidad de Media y Baja Tensión', 'Facultad Tecnológica'),
('573', 'Ingeniería Eléctrica (por ciclos)', 'Facultad Tecnológica'),
('574', 'Tecnología en Mecánica Industrial', 'Facultad Tecnológica'),
('577', 'Tecnología en Gestión de la Producción Industrial', 'Facultad Tecnológica'),
('578', 'Tecnología en Sistematización de Datos', 'Facultad Tecnológica'),
('579', 'Ingeniería Civil', 'Facultad Tecnológica'),
('583', 'Ingeniería en Control y Automatización', 'Facultad Tecnológica'),
('673', 'Tecnología en Electrónica Industrial', 'Facultad Tecnológica'),
('675', 'Ingeniería Mecánica', 'Facultad Tecnológica'),
('676', 'Ingeniería de Producción', 'Facultad Tecnológica'),
('678', 'Ingeniería en Telemática', 'Facultad Tecnológica'),
('052', 'Comunicación Social y Periodismo', 'Facultad de Ciencias y Educación'),
('053', 'Archivística y Gestión de la Información Digital', 'Facultad de Ciencias y Educación'),
('133', 'FORM. DE PROFESORES EN NUEVAS EXPERIENCIAS EDUCATIVAS INCLUYENTES Y SOLIDARIAS', 'Facultad de Ciencias y Educación'),
('134', 'INVESTIGACION Y EXTENSION DE PEDAGOGIA', 'Facultad de Ciencias y Educación'),
('135', 'Licenciatura en Física', 'Facultad de Ciencias y Educación'),
('140', 'Licenciatura en Biología', 'Facultad de Ciencias y Educación'),
('145', 'Licenciatura en Matemáticas', 'Facultad de Ciencias y Educación'),
('150', 'Licenciatura en Química', 'Facultad de Ciencias y Educación'),
('155', 'Licenciatura en Ciencias Sociales', 'Facultad de Ciencias y Educación'),
('160', 'Licenciatura en Humanidades y Lengua Castellana', 'Facultad de Ciencias y Educación'),
('165', 'Licenciatura en Lenguas Extranjeras (Inglés)', 'Facultad de Ciencias y Educación'),
('187', 'Licenciatura en Educación Infantil', 'Facultad de Ciencias y Educación'),
('188', 'Licenciatura en Educación Artística', 'Facultad de Ciencias y Educación'),
('245', 'LICENCIATURA EN MATEMATICAS', 'Facultad de Ciencias y Educación'),
('255', 'LICENCIATURA EN CIENCIAS SOCIALES', 'Facultad de Ciencias y Educación'),
('260', 'LICENCIATURA EN HUMANIDADES Y LENGUA CASTELLANA', 'Facultad de Ciencias y Educación'),
('265', 'LICENCIATURA EN LENGUAS EXTRANJERAS CON ENFASIS EN INGLES', 'Facultad de Ciencias y Educación'),
('287', 'LICENCIATURA EN EDUCACION INFANTIL', 'Facultad de Ciencias y Educación'),
('288', 'LICENCIATURA EN EDUCACION ARTISTICA', 'Facultad de Ciencias y Educación'),
('001', 'Administración Deportiva', 'Facultad del Medio Ambiente y Recursos Naturales'),
('010', 'Ingeniería Forestal', 'Facultad del Medio Ambiente y Recursos Naturales'),
('030', 'TECNOLOGIA EN TOPOGRAFIA', 'Facultad del Medio Ambiente y Recursos Naturales'),
('031', 'Tecnología en Levantamientos Topográficos', 'Facultad del Medio Ambiente y Recursos Naturales'),
('032', 'Ingeniería Topográfica', 'Facultad del Medio Ambiente y Recursos Naturales'),
('081', 'Tecnología en Gestión Ambiental y Servicios Públicos', 'Facultad del Medio Ambiente y Recursos Naturales'),
('085', 'Tecnología en Saneamiento Ambiental', 'Facultad del Medio Ambiente y Recursos Naturales'),
('131', 'TECNOLOGIA EN LEVANTAMIENTOS TOPOGRAFICOS', 'Facultad del Medio Ambiente y Recursos Naturales'),
('180', 'Ingeniería Ambiental', 'Facultad del Medio Ambiente y Recursos Naturales'),
('181', 'Ingeniería Sanitaria', 'Facultad del Medio Ambiente y Recursos Naturales'),
('185', 'Administración Ambiental', 'Facultad del Medio Ambiente y Recursos Naturales'),
('016', 'Artes Plásticas y Visuales', 'Facultad de Artes - ASAB'),
('098', 'Artes Musicales', 'Facultad de Artes - ASAB'),
('102', 'Arte Danzario', 'Facultad de Artes - ASAB'),
('104', 'Artes Escénicas', 'Facultad de Artes - ASAB'),
('107', 'FISICA', 'Facultad de Ciencias Matemáticas y Naturales'),
('108', 'QUIMICA', 'Facultad de Ciencias Matemáticas y Naturales'),
('109', 'BIOLOGIA', 'Facultad de Ciencias Matemáticas y Naturales'),
('167', 'Matemáticas (Pregrado Profesional)', 'Facultad de Ciencias Matemáticas y Naturales'),
('168', 'Química (Pregrado Profesional)', 'Facultad de Ciencias Matemáticas y Naturales'),
('169', 'Física (Pregrado Profesional)', 'Facultad de Ciencias Matemáticas y Naturales'),
('309', 'Biología (Pregrado Profesional)', 'Facultad de Ciencias Matemáticas y Naturales'),
('042', 'ENFERMERIA', 'Facultad de Ciencias de la Salud'),
('105', 'INSTITUTO DE LENGUAS UNIVERSIDAD DISTRITAL', 'Institutos y Otros (Segunda Lengua / IPAZUD)'),
('106', 'INSTITUTO PARA LA PEDAGOGIA, LA PAZ Y EL CONFLICTO URBANO', 'Institutos y Otros (Segunda Lengua / IPAZUD)'),
('132', 'CAPACITACION DOCENTE SEGUNDA LENGUA', 'Institutos y Otros (Segunda Lengua / IPAZUD)')
ON CONFLICT (codigo_plan) DO UPDATE SET nombre = EXCLUDED.nombre, facultad = EXCLUDED.facultad;
